### PR TITLE
Added NetworkCredentials to the HTTP call

### PR DESCRIPTION
**Pull request by RabidDog**
Due to constraints I needed to make use of HTTP authentication. I added this by using the UrlBuilder which parses the Username and Password out of the supplied Uri. Then re added it via the NetworkCredentials before the remote call is made.

If this was omitted by design please feel free to close the pull request.

Thanks

### CODE REVIEW

**Comment by judwhite** [comment]
Hi @RabidDog, just a heads up you're committing with your digiquill email which looks like it's not associated with your GitHub account, not sure if that was intentional.

**Comment by RabidDog** [comment]
@judwhite thanks so much for the heads up. Wasn't intentional.

**Comment by drusellers** [comment]
Hello all and thank you for the pull request. This specific pull request as it stands right now will not get merged in. 

Reasons:

- reformatting code that has nothing to do with the change
- not following existing code conventions
- additional library added that is not a part of the real feature ask (though thanks for the pointer)

**Comment by drusellers** [comment]
Also, no tests were added.

**Comment by drusellers** [comment]
Added in PR 29

**Pull request closed without merging**
